version: '3.8'

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/
    command: npm run dev

  webapp:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app/
    command: npm start
    depends_on:
      - server